### ISSUE TITLE
Installation error & "function contains a loop: org-get-tags"

### ISSUE THREAD

**Issue by jcguu95** [alphapapa/org-ql#107]
Today is the first day I try out `org-ql`. I used `M-x package-install` to install `org-ql`, and it was stuck at the checking process for three times. Emacs hung, and I was forced to cancel the installation by `C-g`. The package was downloaded, but it does not work. In particular, the following error seems to be the problem:

```
Symbol's chain of function indirections contains a loop: org-get-tags
```

If more info is required, please let me know. Thank you very much.

**Comment by alphapapa** [comment]
I can't reproduce this using https://github.com/alphapapa/emacs-sandbox.sh on Emacs 26.3.  The package installs cleanly and without any errors or warnings.

**Comment by jcguu95** [comment]
Thank you for testing. What information can I provide more information to better pinpoint the problem?

**Comment by alphapapa** [comment]
First, try to reproduce using the sandbox script or `emacs -q`.  If you can't, you'll know it's a problem with your config, not the package.

If the problem still occurs, provide software versions and how you installed the relevant software.  Also, enable `debug-on-error` and provide the backtrace from when the error happens.

**Comment by kisaragi-hiu** [comment]
I'm experiencing this as well. This seems to happen because `org-version` is messed up: I'm using Org 9.3, but my `org-version` is still `9.1.9` (the built in version). (After writing that sentence, I figured out that my config was messed up because the version of `straight.el` I was using wasn't setting Org up correctly.) As a result, the

```elisp
(defalias 'org-timestamp-to-time #'org-timestamp--to-internal-time)
```

in line 48 is evaluated, leading to a cyclic chain of function indirections.

To emulate the messed up config, try `(setq org-version "9.1.9")` while using a newer version of Org.

IMO `org-version` is too easily messed up, and I'd prefer avoiding `org-version` altogether:

```elisp
(unless (fboundp 'org-timestamp-to-time)
  (defalias 'org-timestamp-to-time #'org-timestamp--to-internal-time))
(if (get 'org-get-tags-at 'byte-obsolete-info)
    (defun org-ql--get-tags (&optional pos local)
      (org-get-tags pos local))
  (defun org-ql--get-tasg (&optional pos local)
     (org-get-tags-at pos local)))
```

although that may just be my own experience.

**Comment by alphapapa** [comment]
> IMO `org-version` is too easily messed up, and I'd prefer avoiding `org-version` altogether:

On the other hand, it revealed the problem in your config.  ;)

Thanks for sharing what you found.  The problem of a mixed-version Org configuration is not uncommon, and it's not something that third-party Org packages can be expected to handle.

**Comment by jcguu95** [comment]
Thanks.. I still got not good luck to make it work.

**Comment by alphapapa** [comment]
@jcguu95 If you need help with Org, please post on the Org mailing list, reddit.com/r/orgmode, etc.
