### ISSUE TITLE
Byte-compilation obscures lexically-bound variables in query, breaking caching

### ISSUE THREAD

**Issue by toshism** [alphapapa/org-ql#11]
I'm having an issue with (I believe anyway) caching. 

```
(defun tl/test (search)
  (org-ql "~/test.org"
    (and
     (todo)
     (tags search))))
```
with test.org looking something like:
```
* TODO test one   :test:
* TODO nottesttwo :nottest:
```

these two calls both return the first todo.
```
(tl/test "test")
(tl/test "nottest")
```
I suspect caching because if I save the test.org file between the two calls to `tl/test` it works as expected, even if test.org hasn't changed (structure). I'm assuming the save invalidates the cache or something.

Thanks!

**Comment by alphapapa** [comment]
Hi,

Thanks, this is an interesting problem.  Caching is part of the issue, and byte-compiling seems to be another part of it.

Here's what seems to be happening: Caching works by hashing the query function.  When it's byte-compiled, the value of the `search` variable from your function call seems to be obscured, and the query looks the same to the cache, regardless of the value of the variable.  If I remove the byte-compilation of the query function, the cache works as you would expect, depending on the value of the variable.

Of course, I don't want to disable byte-compilation, as I want the increased performance it provides.  So there are a few workarounds you could use in your code:

1.  Use `eval` on a backquoted `org-ql` form.  Like:
```el
(defun tl/test (tag)
  (eval `(org-ql "/tmp/charlie-895b2.org"
           (and (todo)
                (tags ,tag)))))
```
2.  Call the `org-ql--query` function instead, like:
```el
(defun tl/test (tag)
  (org-ql--query "/tmp/charlie-895b2.org"
    `(and (todo)
          (tags ,tag))
    :action (lambda ()
              (org-element-headline-parser (line-end-position)))))
```

Other than that, I don't know how to fix the problem.  I don't know much about how elisp byte-compilation works, whether I'm doing something wrong with it, or if there's a way to fix this while preserving byte-compilation.  I'm tempted to ask Chris Wellons, because he's knowledgeable about elisp byte-compilation, but I'm reluctant to bother him with this, since it's not a package he uses.

**Comment by toshism** [comment]
I see, well thanks for the workaround. I will give that a try. Unfortunately I don't know enough about byte-compilation to be much help on this I'm afraid.

**Comment by alphapapa** [comment]
BTW, I'd be very interested to see how you're finding `org-ql` useful in your projects!  :)

**Comment by toshism** [comment]
Yeah, it's great so far. I've just been using a little custom setup with org-protocol to store my (browser) bookmarks and that side works nice, but I haven't had a smooth way to go the other direction really. I have been playing around trying to get a usable agenda view with no luck. Now that I've discovered org-ql i'm just going to build my own view, possibly even extend it to use org-protocol as well to integrate better with my browser.

So thanks for org-ql, looks like it will make it much easier for me, especially since I'm not much of an emacs-lisp developer.

**Comment by alphapapa** [comment]
FYI, I think this is fixed.  I changed the cache key to use the query sexp rather than the byte-compiled predicate function.

**Comment by AloisJanicek** [comment]
Sadly this doesn't seem to be fixed anymore. I am experiencing exactly the same issue as OP.

**Comment by alphapapa** [comment]
> Sadly this doesn't seem to be fixed anymore. I am experiencing exactly the same issue as OP.

@AloisJanicek Please test in a clean Emacs configuration using https://github.com/alphapapa/emacs-sandbox.sh and the latest version of all packages.  If it still happens, please report basic information like the version of Emacs you're using and an ECM.

**Comment by AloisJanicek** [comment]
In my investigation I discovered several things:

1. Example from OP behaves differently between different major versions of emacs and configs:

- emacs 28, doom-emacs and mine .doom.d: both fn calls return first heading
- emacs 27, doom-emacs and mine .doom.d: on first run both fn calls return correct result but then, after second call was made, first call returns result of the second call
- both emacs 27 and 28, vanilla `emacs-sandbox.sh -i org-ql` and I get: `org-ql--byte-compile-warning: Invalid Org QL query`

2. Issue with mine invalid query construction is maybe even more strange:
I wanted to construct query depending on whether I pass mine function todo query list and whether there there is `aj-org-agenda-filer` set
```lisp
(setq aj-org-agenda-filter '("+job"))
(setq aj-org-agenda-filter nil)
(aj/org-agenda-headlines '(todo "TODO" "NEXT"))
(aj/org-agenda-headlines)
```

When mine function looked like this:
```lisp
(defun aj/org-agenda-headlines (&optional keywords)
  (let* ((tag-filter
          (string-remove-prefix "+" (car aj-org-agenda-filter)))
         (query (if keywords
                    `(and ,keywords
                          (if tag-filter
                              (tags tag-filter) t))
                  `(todo))))
    (print query)))
```
It constructed following query `(and (todo "TODO" "NEXT") (if tag-filter (tags tag-filter) t))` which worked but I had to clear `org-ql-cache` every time I changed value of `aj-org-agenda-filter`.

But when I actually printed `query` for the first time few moments ago I realized the mistake I was doing and rewrote the function in following format:

```lisp
(defun aj/org-agenda-headlines (&optional keywords)
  (let* ((keywords (or keywords '(todo)))
         (tags (when aj-org-agenda-filter
               `(tags ,(string-remove-prefix "+" (car aj-org-agenda-filter)))))
         (query (if tags
                   `(and ,keywords, tags)
                  keywords)))
    (print query)))
```
which returns `(and (todo "TODO" "NEXT") (tags "job"))` and org-ql works as expected for me without the need to clear its cache but at the same time example from OP on the second run of first fn call returns cached example of first run of second fn call.

**Comment by alphapapa** [comment]
The cache is keyed on the query as an unevaluated sexp.  If the sexp refers to variables bound in an outer scope, their value at the time the query is executed will not affect whether cached results are returned.  Note as well that the query is byte-compiled into a function at query time.

This bug was originally reported 18 months ago and closed as fixed 9 months ago.  I don't think the bug exists anymore.  If you think there is a bug, please file a new report from scratch.
