### ISSUE TITLE
Create different agenda view blocks within one view.

### ISSUE THREAD

**Issue by tenpast** [alphapapa/org-ql#124]
Hi Alphapapa,

Thank you for this most excellent library! I've been setting my custom agenda views with org-ql-block, as instructed in your manual, but have been unable to add separate blocks in one view (please take a look at attached image for an example of what I'd like to accomplish). 

I am able to get a separate view with the agenda by appending (agenda) outside the org-ql-block command, but as soon as I try to add a second org-ql-block, not only does it not appear, it also removes the (agenda) block.

![2020-05-29_agenda-blocks-example](https://user-images.githubusercontent.com/43411869/83215460-36351600-a191-11ea-8b49-80aed8621cb7.png)

Is this functionality possible? I'm sorry if I've missed it in your documentation.

Thank you and best regards,
Tenpast

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.

I can't help you because you haven't provided enough information, like the code you are using.

Anyway, the problem is probably that you misunderstand how to use the variable `org-agenda-custom-commands`.  This is a common problem and has nothing to do with `org-ql`.  For some more information, see https://www.reddit.com/r/orgmode/comments/fvbnps/trying_and_failing_to_get_a_custom_orgagenda_view/

**Comment by tenpast** [comment]
Hi,

Yes, sorry about that, it was not a properly asked question. Today I went back to draft it and give you the code snippet and it worked. You are right, org-agenda-custom-commands is complex and I must have made a silly mistake when I tried it before. For future reference, this is the code that worked:

`   (setq org-agenda-custom-commands
	 '(("n" "Next Actions without Schedule or Deadline"
	    ((org-ql-block '(and (todo "NEXT")
				 (not (scheduled))
				 (not (deadline)))
			   ((org-ql-block-header "Next Actions without SCHEDULE OR DEADLINE")))
	     (org-ql-block '(todo "DONE")
			   ((org-ql-block-header "Tasks marked as DONE")))))))`

Thanks again!
