### ISSUE TITLE
A way to autocomplete tags across all org dir

### ISSUE THREAD

**Issue by omarelashkar** [alphapapa/org-ql#144]
Hello,
This package is great, but I just want things to be more systematic for me that when I type M-x org-ql search RET org-directory RET tags:  , and then start typing, I wish if there is an autocomplete every if for the defined tag list instead of typing. 

It would be excellent, however, if the function fetches all the tags in all org-file, even #+FILETAGS. 

Thanks,
Omar

**Comment by alphapapa** [comment]
Hello Omar,

You seem to have three distinct ideas here:

1.  Autocompleting tags when entering a query.
2.  Gathering tags from other files.
3.  Gathering tags from `#+FILETAGS:` headers.

Autocompleting tags could be helpful.  However, it would not necessarily be simple to ensure that the tags offered are the ones the user expects.  It might require opening Org files in Emacs that are not yet open, a process that can be slow--in the event of opening many Org files, it could take a long time, which would not be a good experience for the user.

Gathering tags from files that are not yet open in Emacs could be helpful, but it is probably out-of-scope for this project.  I'd recommend using something like `desktop-mode` to automatically open files in Emacs that you want to be pre-loaded.

Gathering tags from headers should already work through the existing Org code.  If it doesn't, see issue #133.

If you wish to repurpose this issue around the first idea, I'm willing to consider that as a future enhancement, because autocompletion while entering queries could be helpful.  But it's probably a long-term goal for the project, not anything I'd work on soon.

Thanks.

**Comment by omarelashkar** [comment]
Thank you very much. I think I can't trade convenicene for performace. I will close this now

 Thank You,
Omar
