### ISSUE TITLE
Export result from org-ql-search into org/ascii file ?

### ISSUE THREAD

**Issue by reyman** [alphapapa/org-ql#180]
Hi, 

I'm interested to generate an html version of all my GTD task that aggregate a GTD org file + some complex org-ql query that collect Task in my org-roam file. Yes, i could save, bookmark and use org-ql-view, but i'm interested by publishing my day-by-day GTD online to share with my team.

For such project i'm planning to use emacs with --batch to cron each day an gtd.el script that run these queries, convert to org, and org-publish to html.

I see in doc that actually org-ql-search return an agenda view, but is it possible to :
a) to redirect these result as a new timestamped .org file (later published by org-publish) ?
b) to chain/multiply the (a) process in a same script ?

I also posted a question on emacs reddit (https://www.reddit.com/r/emacs/comments/kt650l/script_to_batch_export_my_gtd_task_using_orgql/) because i have another bug on select-window function call with org-roam (https://github.com/org-roam/org-roam/blob/7ad32e8395ce6fdf8ebb50aa4bf1b8315835db34/org-roam-buffer.el#L323 & https://github.com/org-roam/org-roam/issues/1151) on batch :( , but the question about possibility to do that with org-ql remain :) 

Thanks

**Comment by alphapapa** [comment]
Hi,

I don't know exactly what you're asking for.  You could write the org-ql-view buffer to a file easily enough, or you could try exporting it as an Org Agenda buffer (since it's mostly compatible with Org Agenda code), or you could write a custom ACTION function for `org-ql-select` to output HTML for each match.

For batch use, see https://github.com/alphapapa/org-ql/blob/master/examples.org#listing-bills-coming-due

**Comment by reyman** [comment]
Thanks, that highlight me on the path to follow. Which function i need to call to write org-ql-view buffer to a file ?

**Comment by alphapapa** [comment]
Please see the Elisp manual, search for "write" and you should find relevant functions.
