### ISSUE TITLE
custom sort functions pollute cache

### ISSUE THREAD

**Issue by natask** [alphapapa/org-ql#186]
the first call to org-ql-select with a custom sort function works correctly. however subsequent calls return missing list of results. It also affects calls that hit the cache.

This happens because `(sort)` modifies the list. the cache becomes polluted. future calls query the same list from the cache. but because the list is malformed, subsequent applications of the sort function return malformed resulted.

fix by replacing `(sort)` with `(-sort)`, which copies the list before sorting.

**Comment by alphapapa** [comment]
Thanks for reporting. I don't have time to verify this at the moment, but, assuming your analysis is correct, what you propose may not be the best solution, because it would impose a performance penalty, especially with large numbers of results.

**Comment by natask** [comment]
I neglected to mention that org ql's default sort functions are implemented using (-sort).  
https://github.com/alphapapa/org-ql/blob/208e103ecc146db71d878df3bd09c6eb60c2797d/org-ql.el#L1893

Although I share your reservations, aside from solving the bug, the performance is within org ql's current implementation.

**Comment by alphapapa** [comment]
You're right, of course.

I've verified the bug.  I don't quite understand how it's happening, because AFAICT `sort` is being called on a copy of the results produced by `-flatten-n`, but destructive functions can be tricky like that (maybe those Clojure folks are onto something...).

Thanks for your patience.  I'll apply this in the next bug-fix release.
