### ISSUE TITLE
Error when both sort and action-fn are given

### ISSUE THREAD

**Issue by akirak** [alphapapa/org-ql#2]
Hello,

Since sorting is done after `action-fn` is applied [1][2], org-ql raises an error if both of the following conditions are satisfied:

- `action-fn` is a function that does not return an Org element
- `sort` is given as a list

[1] https://github.com/alphapapa/org-agenda-ng/blob/master/org-ql.el#L75
[2] https://github.com/alphapapa/org-agenda-ng/blob/master/org-ql.el#L79

This means you can't use the built-in sorting method if you work on multiple files, right? As far as I understand, org elements do not contain information on the original buffer, so you can't get the marker to each element retrieved by org-ql.

**Comment by alphapapa** [comment]
Hi Akira,

What is the error you got?

I think this is a matter of needing to tidy up the API and docs.  The default `action-fn` for `org-ql` is `identity`.  The lower-level function `org-ql--filter-buffer` calls `org-element-headline-parser`, so Org elements are always returned, unless the `action-fn` returns something different from the Org elements.  And the default sorting functions work on Org elements.

> This means you can't use the built-in sorting method if you work on multiple files, right?

No, you can use multiple files/buffers, and in fact that is the default for the `org-agenda-ng` macro, which uses `(org-agenda-files)`.

> As far as I understand, org elements do not contain information on the original buffer, so you can't get the marker to each element retrieved by org-ql.

I recently added the `:markers` argument to `org-ql`, which adds markers to the Org elements, so you don't need to do that manually.

**Comment by akirak** [comment]
The is the error I got:

```
Wrong type argument: listp, #s(corefighter-item ...
```

And the following is the code:

```emacs-lisp
(org-ql (org-agenda-files)
  (scheduled)
  :action-fn
  (lambda (element)
    (let* ((marker (make-marker))
           (pos (org-element-property :begin element))
           (title (org-element-property :raw-value element)))
      (set-marker marker pos)
      (make-corefighter-item
       ;; FIXME: Make the title format configurable
       :title title
       :action `(org-goto-marker-or-bmk ,marker))))
  :sort (scheduled))
```

> I recently added the :markers argument to org-ql, which adds markers to the Org elements, so you don't need to do that manually.

Such a function is contained in [org-agenda-ng.el](https://github.com/alphapapa/org-agenda-ng/blob/master/org-agenda-ng.el#L126), but not in org-ql. Perhaps you need to move it to org-ql.

**Comment by alphapapa** [comment]
> This is the error I got: Wrong type argument: listp, #s(corefighter-item ...

I'm not sure what's going on there.  A backtrace would help.  But I guess it's because you're using a custom action-fn that doesn't return an Org element, and then using a default sorting function, which expects an Org element.  I guess instead of using the action-fn, you should leave that unspecified, and then map your lambda around the org-ql results, which will be already sorted.

> Such a function is contained in org-agenda-ng.el, but not in org-ql. Perhaps you need to move it to org-ql.

Maybe so.  This is still largely an experimental WIP, but I need help from people like you to get it into shape to meet users' needs.  My org-sidebar package uses it, but that's it, so far.  I would like to publish that, but I need to publish org-ql first, and that means it needs polishing, so...

Anyway, I can move the markers-adding to org-ql, which is probably a good idea.  I'm trying to keep org-agenda-ng and org-ql separated as much as possible, but that is probably generally useful enough that it belongs on the ql side.  So I'll do that soon.

I'm looking forward to seeing what your corefighter package looks like in action.  I'm curious to see how the UI looks.

Thanks very much for your feedback.

**Comment by akirak** [comment]
> I'm not sure what's going on there. A backtrace would help. But I guess it's because you're using a custom action-fn that doesn't return an Org element, and then using a default sorting function, which expects an Org element. I guess instead of using the action-fn, you should leave that unspecified, and then map your lambda around the org-ql results, which will be already sorted.

Yes, that's exactly what's causing this issue. `action-fn` should be intact, but then the result won't contain buffer information, which is bad if I work with multiple Org sources.

> Anyway, I can move the markers-adding to org-ql, which is probably a good idea. I'm trying to keep 

org-agenda-ng and org-ql separated as much as possible, but that is probably generally useful enough that it belongs on the ql side. So I'll do that soon.
Yes, it will solve the issue. Thanks.

**Comment by alphapapa** [comment]
@akirak Please note that I just made some changes to consolidate how arguments are handled between `org-ql` and `org-ql--query`.  Hopefully it will be an improvement.  :)

**Comment by akirak** [comment]
Thank you. The package has gone so far, so this is no longer applicable.
