### ISSUE TITLE
[Q] how to use variables in predicate parameters

### ISSUE THREAD

**Issue by utrack** [alphapapa/org-ql#241]
Hi alphapapa,
Thanks for your work, org-ql is awesome!

I'm still getting the hang of elisp and I can't understand how to pass variables in org-ql queries. Can you help me out?
Here's my current code:
```
(let ((foo '("Bob")))
  (org-ql-search (org-agenda-files)
    '(and
      (not (done))
      (apply 'person foo)
      )))
```
I want it to expand to this:
```
  (org-ql-search (org-agenda-files)
    '(and
      (not (done))
      (person "Bob")
      ))
```

**Comment by yantar92** [comment]
> I'm still getting the hang of elisp and I can't understand how to pass
> variables in org-ql queries. Can you help me out?

For future, note that issue tracker is not the place to ask general
Elisp questions. You can instead try emacs-help mailing list, #emacs
IRC, or emacs subreddit.

Please read "10.4 Backquote" section of Elisp manual.

Instead of

'(and (not (done)) (apply 'person foo))))

you need

`(and (not (done)) (person ,foo))))

**Comment by alphapapa** [comment]
@yantar92 Thank you.  :)

@utrack Thanks for the kind words.  Welcome to Emacsland.  We're a friendly and helpful bunch, we just ask that you generally check documentation first and ask questions in the appropriate places.  You can find me on Reddit at http://old.reddit.com/r/emacs+orgmode
