### ISSUE TITLE
What to do with empty buffers?

### ISSUE THREAD

**Issue by symbiont-matthew-piziak** [alphapapa/org-ql#28]
This package fails on me if I have an empty org buffer. In this case I had archived everything in `empty.org`, then tried to query `agenda` for `(todo "TODO")` with grouping `parent`.

Backtrace:
```
signal(error ("Before first headline at position 21 in buffer emp..."))
error("Before first headline at position %d in buffer %s" 21 #<buffer empty.org>)
org-back-to-heading(t)
org-get-todo-state()
todo("TODO")
#f(compiled-function () #<bytecode 0x17dc9d1>)()
org-ql--select(:predicate #f(compiled-function () #<bytecode 0x17dc9d1>) :action #f(compiled-function () #<bytecode 0x17dc9e5>) :narrow nil)
apply(org-ql--select (:predicate #f(compiled-function () #<bytecode 0x17dc9d1>) :action #f(compiled-function () #<bytecode 0x17dc9e5>) :narrow nil))
org-ql--select-cached(:predicate #f(compiled-function () #<bytecode 0x17dc9d1>) :action #f(compiled-function () #<bytecode 0x17dc9e5>) :narrow nil)
#f(compiled-function (it) #<bytecode 0x17dca09>)(#<buffer empty.org>)
```

**Comment by alphapapa** [comment]
I guess this is a bug, but I'm not completely sure, because if a user is trying to search an empty buffer, something might be wrong, and he might want to know that the buffer is empty.  For myself, if a buffer I searched were empty, that would probably mean that either I tried to search the wrong buffer, or I accidentally erased the buffer, and I'd want to know that rather than simply having no results returned.

What do you think?

**Comment by alphapapa** [comment]
This should be fixed by https://github.com/alphapapa/org-ql/commit/b634647e466a7b25effddfbc535d61251c6629df.  Thanks.
