### ISSUE TITLE
Entries on Repeated Calls to org-ql-search

### ISSUE THREAD

**Issue by rickalex21** [alphapapa/org-ql#306]
I'm having the same issue as #182 . When you do another query it brings up the
same query unless I restart emacs. Another thing is that when I quit it does
not kill all the buffers that the agenda opened. However, in my normal agenda
when I quit (org-agenda-exit) it does kill all the buffers.

What I'm wanting to do is interactively search a given tag in a given list of files.

```lisp
(defun tag (tagQuery)
  "Description"
  (interactive "sTAG: ")
          (org-ql-search '("/home/rick/file1.org" "/home/rick/file2.org")  '(tags  tagQuery)))
```

Thanks

**Comment by alphapapa** [comment]
Please see the Elisp manual, section 10.4 "Backquote".  Your command does not substitute the string you enter each time, so the query is the same each time.

**Comment by rickalex21** [comment]
@alphapapa Thanks for the response, sorry I'm fairly new to emacs I don't 
quite understand the solution. This works, the problem is how would I go
about incorporating a 'tags' only search? 

Another problem is that the buffers remain open from the query. I don't
have this problem in agenda, when I quit (org-agenda-exit) it kills all the
 buffers. It exits the agenda, killing Org buffers loaded by the agenda.

```lisp
(defun my/tag-search (query)
  "Search for tags."
  (interactive (list (read-string "Query: ")))
  (let ((files '("~/file1.org" "~/file2.org")))
    (org-ql-search files query)
    ;; Don't work, searches the same query.
    ;; (org-ql-search files '(tags query))
    ))
```

**Comment by alphapapa** [comment]
> This works, the problem is how would I go
> about incorporating a 'tags' only search?

Please see the `org-ql-find` command, which is designed to allow the user to easily define custom search commands.  You could use the `:query-filter` argument to provide a function that would replace spaces in a string with commas, and the `:query-prefix` argument could be, e.g. `tags:`.

> Another problem is that the buffers remain open from the query. I don't have this problem in agenda, when I quit (org-agenda-exit) it kills all the buffers. It exits the agenda, killing Org buffers loaded by the agenda.

Org QL View buffers are not Org Agenda buffers, even though the former imitates the latter to some extent.  It's not intended that they all be killed by a single command.  If that's functionality you want, you could easily write a command to do so in your Emacs config.  (FYI, since you're new to Emacs: it's common for an Emacs session to have many open buffers--some users with long-running sessions might have hundreds or thousands.  It's not necessary to kill a buffer as soon as you think you're done with it, though you can, of course, if you like.  You might find a tool like Bufler helpful for managing buffers, too: https://github.com/alphapapa/bufler.el)

**Comment by rickalex21** [comment]
Thanks for your help and all the hard work you do. I took your advice and
used the `org-ql-find`. Here is the solution for someone in the future who
may want to do the same thing. 

```lisp
(defun findit (mytags)
  "Finds tags in given files (\"~/file.org\" \"file2.org\") then kills buffers in the list not displayed."
  ;; TODO: :prompt FIND: "Routing" will not show "Static Routing" headline.
  (interactive (list (read-string "Query: ")))
  (org-ql-find (find-org-files-recursively (expand-file-name  (getenv "docs")) "org") :prompt "FIND: " :query-prefix (concat "tags:" mytags))
  (dolist (buf   (find-org-files-recursively (expand-file-name  (getenv "docs")) "org"))
      (if (eq (get-buffer-window (format "%s" (get-buffer (file-name-nondirectory buf))) 'visible) nil)
          (kill-matching-buffers (format "%s*" (file-name-nondirectory buf)) nil t))))
```

It's not a big deal but in the future would like to show the buffer with consult
and figure out why :prompt FIND: "Routing" will not show "Static Routing" headline.
I think that's probably something in:
* selectrum
* my config
* orderless

![org-ql](https://i.imgur.com/7Uw5DxN.png)

**Comment by alphapapa** [comment]
I'm not sure what you mean about the prompt.  That's merely a string displayed to the user before the input.  In your command, you'd probably want to set it to something like `"Find items with tags: "`.  Then you might want to use the filter to replace spaces with commas, so you could type, e.g. `tag1 tag2` instead of `tag1,tag2`, but that's up to you.

A small tip about writing idiomatic Elisp code: Rather than use a "one-armed `if`", use `when` or `unless`.  For example, instead of using `(if (eq FOO nil) ...)`, use `(unless FOO ...)`.

**Comment by rickalex21** [comment]
I changed it to unless. The problem now is that it's limiting the amount of tags found. I usually get about 4-6 tags found when in reality I have 20+ tags. Is there a variable or something preventing org-ql-find from displaying all the tags? `my/tags-search-files` is a list of files.

```lisp
(defalias 'tag 'my/tags-search) 
(defun my/tags-search (tagsQuery)
  "Finds tags in given files (\"~/file.org\" \"file2.org\") then kills buffers in the list not displayed."
  (interactive (list (read-string "Query: ")))
  (unwind-protect 
  (org-ql-find my/tags-search-files :prompt "FIND Tags: " :query-prefix (concat "tags:" tagsQuery )) ; tags requires 2 arguments
  (dolist (buf my/tags-search-files)
      (unless  (get-buffer-window (format "%s" (get-buffer (file-name-nondirectory buf))) 'visible) ; if nil, kill buffers opened by org-ql-find
          (kill-matching-buffers (format "%s*" (file-name-nondirectory buf)) nil t)))))
```
Not sure if it matters but the tag I search is usually a second heading.

```text
:tag 
:Query: someTag
1/3 FIND Tags:
--- somefile.org ---
someTag/Heading 1
--- otherfile.org ---
someTag/Heading 1
-- anotherfile.org--
someTag/Heading 1

```
