### ISSUE TITLE
any way to use org-ql to feed to agenda to render in agenda week/day view ?

### ISSUE THREAD

**Issue by maxandersen** [alphapapa/org-ql#42]
this might be a stupid question - but I can only find ways to have additional blocks added to agenda where as why I would really like is to use org-ql to select a list of todo's and then 'render' them in the agenda week/day view 

Is that possible ?

**Comment by alphapapa** [comment]
Hi Max,

No, org-agenda selects items its own way.  The reason I wrote org-ql is because of how difficult it is to modify org-agenda.  It's intended to be an alternative implementation of similar ideas.  The org-ql-block feature is a neat hack, but that's as far as integration between the two can go.

You can see some examples in the documentation of org-ql queries that produce results similar to org-agenda views.

**Comment by maxandersen** [comment]
Ok, so no way to have timegrid in superagenda with items JUST from org-ql ?

**Comment by alphapapa** [comment]
org-super-agenda only groups strings gathered by org-agenda or org-ql.  The time grid is created by org-agenda.  org-ql-agenda/org-ql-search does not create a time grid at this time, but it's an idea I might work on in the future.

**Comment by maxandersen** [comment]
thanks for the answer - closing.
