### ISSUE TITLE
Pcase change in Emacs master (30) branch causes "Please avoid it" error

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/org-ql#433]
[Apologies for earlier pinging the wrong "Monnier" account on GitHub.  :)  Oops.]

@monnier As reported starting at [this comment](https://github.com/alphapapa/org-ql/issues/232#issuecomment-2163256013), the Pcase-related change in emacs.git commit 16fc5b6c0c72464a75d9a84b754375662b3acec6 has caused a breakage in Org QL: now trying to run some queries (which are parsed and optimized using Pcase expressions) signals a "Please avoid it" error.

The code in question works fine on master before that commit, and on earlier versions of Emacs.

Is this a bug in that commit, or is it now exposing a bug in downstream software?

Thanks.

(Backtrace is in an attachment because GitHub won't accept it in this form.)
[backtrace.txt](https://github.com/user-attachments/files/15830922/backtrace.txt)

**Comment by whudwl** [comment]
Could you have at-ed the wrong monnier?

**Comment by alphapapa** [comment]
> Could you have at-ed the wrong monnier?

Oops, yes, thanks.  I forgot that Stefan is simply @monnier.

**Comment by monnier** [comment]
I haven't investigated very far, but IIRC this error is signaled when Pcase encounters a "silly or" with a single branch.
IOW, my crystal ball suggests that you can avoid that error by changing `org-ql-defpred` so as to avoid wrapping `(quote ,it)` inside an `or` when `predicate-names` has a single element (when computing `normalizers` and `preambles`).

**Comment by akirak** [comment]
Now org-ql fails to byte-compile with "Please avoid it" error on Emacs master.

Commenting out the following expression inside `org-ql--define-query-preamble-fn` seems to prevent the issue

https://github.com/alphapapa/org-ql/blob/d5269bb5e283f3b12b45fb05c4a7926d23e07d1f/org-ql.el#L1144

which is evaluated during the following top-level expression:

https://github.com/alphapapa/org-ql/blob/d5269bb5e283f3b12b45fb05c4a7926d23e07d1f/org-ql.el#L2398

I guess this byte-compilation is intended for performance optimization, but the Emacs byte compiler has been under significant changes to make it more strict, so it's understandable that some existing code may not work. Perhaps nested byte-compilation is no longer allowed because it hinders further optimization by the byte compiler.

**Comment by akirak** [comment]
I followed the comment by @monnier 

> Pcase encounters a "silly or" with a single branch

and [this change](https://github.com/akirak/org-ql/commit/50b29c312baf28faf7a9cb488d720910306dffac) seems to fix the error. At least, it vanishes the "Please avoid it" error both at compile time and runtime.

I am not sure which party should handle this normalization, but we now seem to know the cause.

**Comment by monnier** [comment]
> @monnier Thank you for digging into that.  May I ask, would it be reasonable
> for Pcase to optimize this case away instead of signaling an error about it?
> I think it's not uncommon to use Pcase as a sort of simple
> compiler/optimizer, and if an `(or FOO)` could just be optimized to `FOO` by
> Pcase...why not?  :)  (Or maybe there's a good reason that I don't know of.)

It does sound quite reasonable, indeed.  I can't remember why it signals
an error, and looking at the code doesn't give me an
immediate enlightenment.  I suggest you `M-x report-emacs-bug`.

My best guess is that it was inconvenient to handle it, and I assumed
the patterns would be written by humans so I decided it was OK to tell
them to avoid such silly patterns.

**Comment by alphapapa** [comment]
I think this can, and probably should be, applied in a v0.8.9 release, so reopening and assigning to that milestone.
