### ISSUE TITLE
`org-ql-view--font-lock-as-org`'s buffer causes query on calling `save-some-buffers`

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/org-ql#471]
See https://github.com/alphapapa/org-ql/pull/470

**Comment by a42i** [comment]
So far, it appears, that invoking org-mode when creating the ` *org-ql-view--font-lock-as-org*` buffer sets `buffer-save-without-query` to `t` and `save-some-buffers` will then unconditionally save the buffer.

It seems likely that this may be due to my local setup or some other Org related package. I'll investigate more when I get some time and provide an update.

**Comment by a42i** [comment]
I cannot reproduce this bug with a minimal Emacs + Org + org-ql setup @alphapapa. 

The creation of the ` *org-ql-view--font-lock-as-org*` buffer doesn't set `save-without-query` to `t` and everything functions as it should. 

I haven't isolated the problem in my own setup yet, but I am confident that the issue does not lie with Emacs, Org, or org-ql. I should have done this before opening the pull request. Apologies, and thanks for your patience.

Please close this issue.

**Comment by alphapapa** [comment]
@a42i No problem, this being Emacs, none of us are immune to making this mistake.  I still do sometimes.  :)  Thanks.
