### ISSUE TITLE
possible for a todo/headline to be displayed again in multiple groups?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-ql#52]
I suspect the answer to this is no, since it sort of goes against how the agenda fundamentally works, nevertheless:

If I have two groups, one that captures completed items & one that captures items tagged `:TODAY:`, and a headline could be part of both (i.e. is completed & tagged `:TODAY:`` is there a way to have `org-ql` repeat the task in both?

btw: sorry for all the spam, this tool has already been a game-changer for how I use org, so thank you so much!

**Comment by alphapapa** [comment]
The `org-ql-view` buffers imitate Org Agenda buffers, and grouping is provided by `org-super-agenda`, not by `org-ql`.  

And you're right, the answer is no.  :)  `org-super-agenda` is designed to only display items in the first matching group.  It would theoretically be possible to make a special kind of group that passed through matching items rather than consuming them, so feel free to post an issue on the `org-super-agenda` tracker.  But I can't promise I'll work on implementing such a feature.  :)

**Comment by xeijin** [comment]
Thanks for the explanation, I can see this causing other issues too (e.g. running bulk actions on the same action in multiple groups without refreshing in between) so I think I will try and re-think my groupings/approach.

**Comment by xeijin** [comment]
Worth noting, I manage to implement this with `org-ql-block` since it runs its query on a fresh batch of TODOs each time, it's possible to use it to show duplicate entries on the same agenda in combination with `org-agenda-custom-commands`.

**Comment by alphapapa** [comment]
Cool!
