### ISSUE TITLE
Symbol's function definition is void: org-ql-block

### ISSUE THREAD

**Issue by gcantieni** [alphapapa/org-ql#53]
Hi there, for me it looks like `org-ql-block` is pointing to a non-existent function. When I run the example usage:
```
(setq org-agenda-custom-commands
      '(("t" "Custom: Agenda and Emacs SOMEDAY [#A] items"
         ((org-ql-block '(and (todo "SOMEDAY")
                              (tags "Emacs")
                              (priority "A"))
                        ((org-ql-block-header "SOMEDAY :Emacs: High-priority")))
          (agenda)))))
```
When I try to run this I get `Symbol's function definition is void: org-ql-block`. Additionally, when I call `describe-function` on `org-ql-block` I get:
```
org-ql-block is an alias for ‘org-ql-search-block’, which is not
defined.  Please make a bug report.


Not documented.
```

**Comment by alphapapa** [comment]
Hi,

That alias is autoloaded, so if it isn't working, I guess the package isn't installed correctly.

**Comment by alphapapa** [comment]
@gcantieni Thanks for your report.  Comments on https://github.com/alphapapa/org-ql/issues/75 have shown that there is a bug here.  Steps to reproduce from my comments there:

1.  Start a clean Emacs config in a sandbox using https://github.com/alphapapa/alpha-org/blob/master/emacs-sandbox.sh.
2.  `M-x package-install RET org-ql RET`.
3.  Make and save test file:
```
* [#A] Heading                                                        :Emacs:
blah
```
4.  Add to agenda files with `C-c [`.
5.  Evaluate this Elisp:
```el
(let ((org-agenda-custom-commands
       '(("a" ""
	  ((org-ql-block '(and 
                              (tags "Emacs")
                              (priority "A"))
			 ((org-ql-block-header ":Emacs: High-priority"))))))))
  (org-agenda nil "a"))
```

Output:
```
:Emacs: High-priority
  [#A] Heading                                                                                  :Emacs:
```

6.  Kill Emacs.
7.  Restart Emacs with the same config.
8.  Re-open the Org file.
9.  Repeat steps 4 and 5.

Result: A backtrace saying that `org-ql-block` is a void function.

However, then:

10.  `C-h f org-ql-block RET` to show the help buffer:
```
org-ql-block is an alias for ‘org-ql-search-block’ in
‘org-ql-search.el’.
```
Then:

11.  Repeat step 5.

Result: the agenda block is displayed properly, without error.

Also, these steps seem to indicate that the alias is loaded into Emacs, but the function is still void:

12.  Exit Emacs.
13.  Restart Emacs with the same config.
14.  `C-h f org-ql-block RET`.

Result:

```
org-ql-block is an alias for ‘org-ql-search-block’ in
‘org-ql-search.el’.

(org-ql-block QUERY)

Insert items for QUERY into current buffer.
...
```
Unlike the error message reported by @gcantieni, this shows that `org-ql-search-block` is loaded and defined, but when the example agenda code is run, the alias function is void.  Loading `org-ql-search` fixes the problem, but it shouldn't be necessary, because the autoload should take care of it.

`org-ql-search.el` defines the alias like this:

```el
;;;###autoload
(defalias 'org-ql-block 'org-ql-search-block)
```

For some reason that's not causing the alias to work, even though `describe-function` shows that it is loaded.  More investigation will be required.

In the meantime, users can `(require 'org-ql-search)` in their Emacs configs to force the file to load and define the function and alias.
