### ISSUE TITLE
org-ql Package In Melpa Stable Has Requirement On Package In Regular Melpa

### ISSUE THREAD

**Issue by tompurl** [alphapapa/org-ql#54]
The ``org-ql`` package in Melpa Stable requires ``org-super-agenda`` >= 1.2-1, but the most current version of ``org-super-agenda`` available in Melpa stables is 1.1.1.

I don't know if this is the proper place for a bug like this, so I apologize in advance if that's the case. In the end I would like to be able to install ``org-ql`` using Melpa Stable.

**Comment by alphapapa** [comment]
Sorry about that.  I need to tag another version of org-super-agenda.  But there are a few issues and PRs I want to get to first.

Generally, I can't recommend actually using MELPA Stable, because issues like this can be expected to occur.  Package authors (like myself) don't develop with MELPA Stable in mind: as you can see, conflicts occur between packages by the same author--and since there is no coordination between packages, imagine the conflicts between packages by different authors.  Most authors don't tag "stable" versions of their packages at all; some do so when asked to by people who want to use MELPA Stable, but that without any planning or coordination regarding versions, upgrades, etc.  So issues like this are inevitable.  Unfortunately, MELPA Stable is not at all like a counterpart to Debian Stable.

For my own packages, tagged versions are mainly a way to help organize the development of the package, helping users track changes in the changelog, separating bugfix changes from other types, etc.

In this case, I would recommend installing the current version of org-super-agenda yourself, e.g. with `quelpa-use-package` like this:

```el
(use-package org-super-agenda
  :quelpa (org-super-agenda :fetcher github :repo "alphapapa/org-super-agenda"))
```

You can then upgrade it manually when you're ready, or you can switch back to installing it from MELPA or MELPA Stable when the time comes.

**Comment by tompurl** [comment]
Wow, this is an excellent and informative response. Thank you for the thorough explanation.
