### ISSUE TITLE
Could we map `org-ql-view-refresh` to 'r' in org-ql-view buffers?

### ISSUE THREAD

**Issue by xeijin** [alphapapa/org-ql#58]
Right now pressing the 'r' key in a search buffer shows the message `Rebuilding agenda...` but doesn't actually refresh. I'm guessing because this isn't a 'true' agenda buffer. If that's the case could we remap `org-ql-view-refresh` to 'r' instead which does refresh it as desired?

**Comment by alphapapa** [comment]
The `g` key is bound to `org-ql-view-refresh`.  `g` seems to be the standard key binding for refreshing most such buffers in Emacs.  In Org Agenda buffers, `r` is a different command that does something subtly different (see documentation).  The `org-ql-view-refresh` command could also be bound to `r`, but I think we shouldn't do that, because it might be useful to bind that to something else in the future.  You can do that in your own config if you like.

**Comment by xeijin** [comment]
@alphapapa it looks like a clash with `evil-org-agenda-mode-map` caused this so agree with your assessment, the existing mapping to `g` should suffice.
