### ISSUE TITLE
helm-org-ql: void-function peg-parse-string

### ISSUE THREAD

**Issue by novoid** [alphapapa/org-ql#75]
After installing `org-ql-20191207.408` via use-package (yes, I switched from GitHub version to use-package because of list of dependencies) I get this when invoking `helm-org-ql`:

```
Error running timer: (error "In ‘helm-org-ql’ source: ‘#[0 \\303	!\\304\\305 !\\205%\0r\\306 q\\210\\300)\\3071#\0\\310\\300\\311\\312D$0\\202%\0\\210\\313\\207 [issues.org helm-pattern helm-org-ql-buffers-files org-ql--plain-query window-width helm-window helm-buffer-get (error) org-ql-select :action helm-org-ql--heading nil] 8]’ 
 (void-function peg-parse-string)")
```

Initial tests of `org-ql-search` do seem to work though.

Some package versions I do think might be involved:
- helm-org-20191214.802
- org-ql-20191207.408
- ts-20191010.210
- peg-1.0
- ov-20191127.32
- dash-functional-20191109.1327
- org-sidebar-20191012.514

**Comment by alphapapa** [comment]
Hi Karl,

Just FYI, `use-package` doesn't install packages.  The `:ensure t` keyword argument to the macro causes it to attempt to ensure the package is installed using the built-in `package.el`.  The distinction can be important, because, e.g. there are other ways that `use-package` can cause packages to be installed, e.g. with `quelpa-use-package`, `straight.el`, etc, which provide `use-package` keyword add-ons and don't use `package.el` as a backend to install a package.

That error indicates that the `peg` package is not installed.  I would recommend uninstalling `org-ql` completely (e.g. you could use this function: https://github.com/alphapapa/unpackaged.el#delete-all-installed-versions-of-a-package), then restart Emacs, then reinstall `org-ql` and ensure that there are no errors from the full installation process, which should include dependencies.

**Comment by alphapapa** [comment]
By the way, you might find this script helpful for testing Emacs in a clean configuration: https://github.com/alphapapa/alpha-org/blob/master/emacs-sandbox.sh

**Comment by novoid** [comment]
You're a true Emacs wizard.

I used your script to remove org-sidebar, org-ql, and peg. Out of curiosity I just re-started Emacs to find out if use-package is able to install it cleanly this time. And yes, **it works now**, even solves #76 as you already knew.

Related to your FYI: I already knew that use-package with `:ensure t` uses `package.el` to install. What was the difference between the first install of line and the second after deleting the packages? And why was there a `peg-1.0` folder in my elpa directory? Or was v1.0 simply too old?

Thanks for your explanations!

**Comment by alphapapa** [comment]
> You're a true Emacs wizard.

I'm a noob compared to the real wizards.  ;)

> I used your script to remove org-sidebar, org-ql, and peg. Out of curiosity I just re-started Emacs to find out if use-package is able to install it cleanly this time. And yes, **it works now**, even solves #76 as you already knew.

Great!

> Related to your FYI: I already knew that use-package with `:ensure t` uses `package.el` to install. What was the difference between the first install of line and the second after deleting the packages? And why was there a `peg-1.0` folder in my elpa directory? Or was v1.0 simply too old?

I don't know what the problem was, but chances are it was due to outdated packages with stale .elc files that Emacs was loading in preference to the newer versions; it's a common issue.  Or perhaps one of the packages failed to install at some time in the past, and it wasn't noticed until now.  Deleting old versions and installing newer ones usually fixes things like that.

If that happens again, it may indicate a kind of configuration problem.  You might want to redo the part of your config that configures the package system, `load-path`, etc.

> Thanks for your explanations!

The least I can do for someone like you who contributes so much to the Emacs/Org community!

**Comment by novoid** [comment]
Something's fishy here. I get this again:
```
org-ql-block is an alias for ‘org-ql-search-block’, which is not defined.
```

I get rid of `org-ql` and `peg` using your function, restart emacs, packages get fetched and installed, everything's working fine. The I restart emacs and the error re-appears. 

Could it be related to the order I load the packages? I committed my recent changes, if you need to take a look: https://github.com/novoid/dot-emacs/blob/master/config.org

Having re-started my emacs for a couple of hundred times today, I'm happily volunteering in debugging this, if this helps.

**Comment by alphapapa** [comment]
> I get rid of org-ql and peg using your function, restart emacs, packages get fetched and installed, everything's working fine. The I restart emacs and the error re-appears.

When exactly does the error appear?  Simply after restarting Emacs, without actually *doing* anything in Emacs?

> Could it be related to the order I load the packages?

Probably, yes.  Try loading `org-ql` before anything that might use it or the agenda.

**Comment by yantar92** [comment]
> Having re-started my emacs for a couple of hundred times today, I'm happily volunteering in debugging this, if this helps.

As a blind shot, could you try setting load-prefer-newer to t before (package-initialize)?

**Comment by rieje** [comment]
I am also having the same problem. I tried both use-package to install and then installing it manually via `package-list-packages` (`rm -rf ~/.emacs.d/elpa/org-ql*` before each install. Also have `load-prefer-newer` to `t`.

`org-ql-block` only works if I run `org-ql-search` beforehand. I assume I'm a noob and am missing something? Isn't `use-package` supposed to auto-load to take care of this?

**Comment by alphapapa** [comment]
I have verified, again, that `org-ql-block` works properly.

1.  Start a clean Emacs config in a sandbox using https://github.com/alphapapa/alpha-org/blob/master/emacs-sandbox.sh.
2.  `M-x package-install RET org-ql RET`.
3.  Make and save test file:
```
* [#A] Heading                                                        :Emacs:
blah
```
4.  Add to agenda files with `C-c [`.
5.  Evaluate this Elisp:
```el
(let ((org-agenda-custom-commands
       '(("a" ""
	  ((org-ql-block '(and 
                              (tags "Emacs")
                              (priority "A"))
			 ((org-ql-block-header ":Emacs: High-priority"))))))))
  (org-agenda nil "a"))
```

Output:
```
:Emacs: High-priority
  [#A] Heading                                                                                  :Emacs:
```

If it doesn't work properly in your system, you either have a configuration error or the package is not installed correctly.

**Comment by jakejx** [comment]
> Something's fishy here. I get this again:
> 
> ```
> org-ql-block is an alias for ‘org-ql-search-block’, which is not defined.
> ```
> 
> I get rid of `org-ql` and `peg` using your function, restart emacs, packages get fetched and installed, everything's working fine. The I restart emacs and the error re-appears.
> 
> Could it be related to the order I load the packages? I committed my recent changes, if you need to take a look: https://github.com/novoid/dot-emacs/blob/master/config.org
> 
> Having re-started my emacs for a couple of hundred times today, I'm happily volunteering in debugging this, if this helps.

Here to report that I am facing the same issue. I am running spacemacs on Emacs 27. When I install the package, the autoloads seem to work properly. But once I restart Emacs, and run my agenda, I get `Symbol’s function definition is void: org-ql-block`.

I'll try to debug and see whats causing the issue.

**Comment by alphapapa** [comment]
@jakejx Thanks, I see the problem now.  I've reopened #53; please see my comment there.

**Comment by karlicoss** [comment]
Hey, so I reinstalled my OS recently, freshly cloned my emacs setup and the `void-function peg-parse-string` started happening! 
I'm using `org-ql 0.4.5 (c847afe)`.

I investigated a bit and it seems that in the most recent version of peg this function was moved to [peg-tests.el](https://github.com/emacs-straight/peg/blob/master/peg-tests.el#L29). I even tried `(require 'peg-test)` and retrying `org-ql-search`, but then ran into [this error](https://github.com/emacs-straight/peg/blob/master/peg.el#L463-L464).

After digging a bit more, it seems that [org-ql](https://github.com/alphapapa/org-ql/blob/c847afe0b538a1a44c73e40b067831cbea132ba7/org-ql.el#L6) requires 0.6, whereas in my Doom package has the version 1.0. Not sure if Doom is to blame -- frankly I don't know much about Emacs packaging -- does "0.6" mean minimum version, or exact version? [Elpa](https://elpa.gnu.org/packages/peg.html) only has 1.0 (does it keep the history at all?), and the oldest commit in the emacs-straight mirror is [0.7](https://github.com/emacs-straight/peg/blob/dad2405312c4f95a064b7d739096d71652799984/peg.el#L7). Not sure where to get 0.6, but I tried using 0.7 and it seems to work!

**Comment by alphapapa** [comment]
@karlicoss Thanks, I think I see the problem now.  The macro `peg-parse-string` was indeed moved to `peg-tests.el`, and in version 1.0 of `peg` on ELPA, that's where it is.  But in the version I have installed in my config, it's still present in `peg.el`, so this error does not present itself.

Normally this problem would be detected by my testing in a clean Emacs configuration.  However, when I follow these steps in a clean config:

1.  Install `helm-org`.
2.  Install `org-ql`.
3.  `M-x describe-function RET peg-parse-string RET`

The macro `peg-parse-string` is found as having been loaded from `peg-tests.el`.  I think this is an idiosyncrasy of the `package-install` process and the fact that `peg-tests.el` is present in the ELPA package (test files are not usually present in installed Emacs packages).  Because of that, this error was masked in my testing.

I wish that function hadn't been moved to the test file, but it should be a simple fix to implement its equivalent in this package, which should fix the problem.

Thanks for following up with those details.

**Comment by alphapapa** [comment]
@novoid @karlicoss I think that should fix it.  I tested manually in a clean configuration (keeping in mind the issues I mentioned), and it seems to work properly.  Please let me know how it works for you.

**Comment by novoid** [comment]
I currently can not reproduce the issue since my `org-ql` isn't working at all (see #129).

I can't use my previous workaround with re-installing `org-ql` because there is no "uninstall" button for `org-ql` in my `list-packages` any more because(?) it is installed as a dependency for something.

**Comment by karlicoss** [comment]
@alphapapa thanks, pulled your latest change and it worked! :+1:

**Comment by alphapapa** [comment]
> I currently can not reproduce the issue since my `org-ql` isn't working at all (see #129).
> 
> I can't use my previous workaround with re-installing `org-ql` because there is no "uninstall" button for `org-ql` in my `list-packages` any more because(?) it is installed as a dependency for something.

It's getting confusing discussing this problem in two issues.  I suspect your problem may be fixed by the fix to this issue, but let's discuss your problem in #129.

**Comment by novoid** [comment]
Purging my packages and re-installing them from scratch, pulling the updates solved the issue on my side.

Thanks for your help!
